### ISSUE TITLE
Associated types not supported in declarations

### ISSUE THREAD

**Issue by claudemarche** [creusot-rs/creusot#213] opened 2021-11-08 11:12 UTC
On the code
```
extern crate creusot_contracts;
use creusot_contracts::{std::vec::Vec};

fn main() {
    let mut door_open : Vec<bool> = Vec::with_capacity(100);
    for pass in 1..101 {
        let mut door = pass;
        while door <= 100 {
            door_open[door - 1] = !door_open[door - 1];
            door += pass;
        }
    }
}
```
the 'mlcfg' Creusot command succeeds, but the generated MLCFG code is wrong: 
```
> why3 prove -L prelude 100doors.mlcfg
File "100doors.mlcfg", line 53, characters 86-96:
unbound type symbol 'Item0.item'
```

**Comment by xldenis** [comment] 2021-11-22 12:54
The issue is because of 

```
pub struct Peekable<I: Iterator> {
    iter: I,
    /// Remember a peeked value, even if it was None.
    peeked: Option<Option<I::Item>>,
}
```

Currently Creusot can't properly translate associated items in types.

**Comment by xldenis** [comment] 2024-09-24 12:43
Fixed in master.

**Closed by xldenis** 2024-09-24 12:43 UTC
Labels: bug, error-messages
