### ISSUE TITLE
Could not find loop header

### ISSUE THREAD

**Issue by sarsko** [creusot-rs/creusot#164] opened 2021-10-20 18:44 UTC
Early returns in while-loops, as in:
```
fn example() -> bool {
    let mut j = 0;
    let loop_len = 5;
    #[invariant(loop_bound2, 0usize <= j && j <= loop_len)]
    while 0 < 5 {
        return true;
    }
    return true;
}
```
Gives the following error `thread 'rustc' panicked at 'Could not find loop header', creusot/src/gather_invariants.rs:146:17`

**Comment by jhjourdan** [comment] 2024-11-18 09:43
This is in fact more serious than we thought. Consider the following example:

```rust
extern crate creusot_contracts;
use creusot_contracts::*;

fn example() -> bool {
    let mut j = 0;
    let loop_len = 5;
    #[invariant(0usize <= j && j <= loop_len)]
    loop {

        j = loop_len + 1;
        loop {

        }

        return true;
    }
    return true;
}
```


Here, the invariant is attached to the second loop, not the first one.

**Comment by jhjourdan** [comment] 2024-11-18 09:48
We need a better way to detect this problem, and then 1- emit a warning and 2- emit an assert, because this is equivalent to a loop invariant in this case.

In order to better detect this problem, I propose to make the `#[invariant]` macro insert a special instruction at the beginning of the loop body, which we would use to stop the search for a loop entry, instead of a switch.

**Comment by Lysxia** [comment] 2024-11-22 11:55
The current heuristic to detect loop headers is to find the earliest successor that dominates itself. But, as far as I can tell, the loop header is always the next block after the one that contains the invariants, even if the loop is a fake loop that immediately breaks or returns (for which the current heuristic fails). If so, we can remove the heuristic and immediately attach the invariant to the next block. Is there a situation where that won't work?

**Comment by jhjourdan** [comment] 2024-11-22 13:30
This may work, but in my opinion this relies way too much on how the compiler works. It may ad or remove NOP blocks in the future. Also, I have not audited rustc's code, so I am not even sure there are no corner cases where this does not apply.

The more I think about this the more tricky I find to have a satisfying solution. The last thing that came to my mind is to syntactically convert all the loop forms into the `loop { ... }` construct, with a special marker at the beginning of the loop body which would prevent us to search too far. If, in addition, we make sure that we only skip no-op blocks, this seems to be quite a robust mechanism.

A good translation of  `while let ... { ... }` could be `loop{ if let ... { ... } else { break } }`, which, I think, is completely syntactically equivalent.

(Of course, if in the end we only use the `loop` construct, then we can move the invariant declaration inside the loop body, as you proposed initially, but you would still have to do a backward search to find the header, and we would still have to find a mechanism to make sure that we don't backward search too far...)

**Comment by xldenis** [comment] 2024-11-22 14:12
another option could be to just turn the invariant into an assertion if we can't find the loop header (without moving it) and emit a warning?

**Comment by jhjourdan** [comment] 2024-11-22 14:18
See https://github.com/creusot-rs/creusot/issues/164#issuecomment-2482437263 : in fact, the problem is more serious than the issue suggests : in some cases, invarians are attached to the wrong loop.

**Comment by Lysxia** [comment] 2024-11-22 14:38
I think @jhjourdan's proposal to desugar all loops using `loop` is the way to go.

The problem is that we can't detect the absence of a loop header because any heuristic will end up detecting a neighboring loop. The solution is to introduce a marker to bound the search for a loop header. A complication then is that for `while` loops, there is no good place to insert such a marker, because it must be "before" the condition, which may contain loops. I don't see another way than to rewrite all loops using `loop`, which doesn't seem too problematic because we already do that for `for`, and we won't see the difference in MIR anyway.

We could also forbid loops in `while` conditions, but that seems no easier to implement than doing the generally correct thing in the first place.

**Closed** 2024-11-29 21:35 UTC
Labels: bug
