### ISSUE TITLE
Forbid uninhabited types

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#114] opened 2021-10-06 11:50 UTC
In why3 types are always inhabited, to ensure that we don't cause issues or accidentally introduce unsoundness, we should forbid any empty type from being translated into why3, except for `!`. 

In particular this means ruling out:

1. Empty sums `enum Empty {}`
2. Co-recursive types `struct Stream<T> { hd: T, tl: Box<Stream<T>>}`. Ok, sure it's not _uninhabited_ but it has no finite inhabitant which is the same thing for us.

**Comment by Lysxia** [comment] 2024-09-11 12:26
Just to make sure, in Rust there is no value of type `struct Stream<T> { hd: T, tl: Box<Stream<T>>}`, is there?

Otherwise we can close this as duplicate of #881

**Closed as completed** 2024-09-11 13:17 UTC
Labels: soundness
